// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.4
// source: api/specs/specs.proto

package specs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MachineSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	AmiId         string                 `protobuf:"bytes,3,opt,name=ami_id,json=amiId,proto3" json:"ami_id,omitempty"`
	InstanceType  string                 `protobuf:"bytes,4,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineSpec) Reset() {
	*x = MachineSpec{}
	mi := &file_api_specs_specs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineSpec) ProtoMessage() {}

func (x *MachineSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_specs_specs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineSpec.ProtoReflect.Descriptor instead.
func (*MachineSpec) Descriptor() ([]byte, []int) {
	return file_api_specs_specs_proto_rawDescGZIP(), []int{0}
}

func (x *MachineSpec) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *MachineSpec) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *MachineSpec) GetAmiId() string {
	if x != nil {
		return x.AmiId
	}
	return ""
}

func (x *MachineSpec) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

var File_api_specs_specs_proto protoreflect.FileDescriptor

const file_api_specs_specs_proto_rawDesc = "" +
	"\n" +
	"\x15api/specs/specs.proto\x12\bawsspecs\"\x82\x01\n" +
	"\vMachineSpec\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x15\n" +
	"\x06ami_id\x18\x03 \x01(\tR\x05amiId\x12#\n" +
	"\rinstance_type\x18\x04 \x01(\tR\finstanceTypeB9Z7github.com/siderolabs/omni-infra-provider-aws/api/specsb\x06proto3"

var (
	file_api_specs_specs_proto_rawDescOnce sync.Once
	file_api_specs_specs_proto_rawDescData []byte
)

func file_api_specs_specs_proto_rawDescGZIP() []byte {
	file_api_specs_specs_proto_rawDescOnce.Do(func() {
		file_api_specs_specs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_specs_specs_proto_rawDesc), len(file_api_specs_specs_proto_rawDesc)))
	})
	return file_api_specs_specs_proto_rawDescData
}

var file_api_specs_specs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_specs_specs_proto_goTypes = []any{
	(*MachineSpec)(nil), // 0: awsspecs.MachineSpec
}
var file_api_specs_specs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_specs_specs_proto_init() }
func file_api_specs_specs_proto_init() {
	if File_api_specs_specs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_specs_specs_proto_rawDesc), len(file_api_specs_specs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_specs_specs_proto_goTypes,
		DependencyIndexes: file_api_specs_specs_proto_depIdxs,
		MessageInfos:      file_api_specs_specs_proto_msgTypes,
	}.Build()
	File_api_specs_specs_proto = out.File
	file_api_specs_specs_proto_goTypes = nil
	file_api_specs_specs_proto_depIdxs = nil
}
